### 모델 생성 및 평가

In [3]:
import pandas as pd
df = pd.read_csv("data/loan_train_cleaning.csv")
df.head().T #컬럼/인덱스 좌우 위치 바꿔줌 (컬럼 많을 경우 확인 용이)

                        0       1       2       3       4
Loan_ID               0.0     1.0     2.0     3.0     4.0
Gender                1.0     1.0     1.0     1.0     1.0
Married               0.0     1.0     1.0     1.0     0.0
Dependents            0.0     1.0     0.0     0.0     0.0
Education             0.0     0.0     0.0     1.0     0.0
Self_Employed         0.0     0.0     1.0     0.0     0.0
ApplicantIncome    5849.0  4583.0  3000.0  2583.0  6000.0
CoapplicantIncome     0.0  1508.0     0.0  2358.0     0.0
LoanAmount          128.0   128.0    66.0   120.0   141.0
Loan_Amount_Term    360.0   360.0   360.0   360.0   360.0
Credit_History        1.0     1.0     1.0     1.0     1.0
Property_Area         2.0     0.0     2.0     2.0     2.0
Loan_Status           1.0     0.0     1.0     1.0     1.0

### 머신러닝 변수
* label : 종속 변수 또는 정답
* feature : 독립 변수 또는 속성

In [4]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [5]:
features = ['Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area']
label = 'Loan_Status'
X, y = df[features] , df[label]

In [7]:
X.T

                      0       1       2       3       4       5    ...     608     609     610     611     612     613
Gender                1.0     1.0     1.0     1.0     1.0     1.0  ...     1.0     0.0     1.0     1.0     1.0     0.0
Married               0.0     1.0     1.0     1.0     0.0     1.0  ...     1.0     0.0     1.0     1.0     1.0     0.0
Dependents            0.0     1.0     0.0     0.0     0.0     2.0  ...     0.0     0.0     3.0     1.0     2.0     0.0
Education             0.0     0.0     0.0     1.0     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0
Self_Employed         0.0     0.0     1.0     0.0     0.0     1.0  ...     0.0     0.0     0.0     0.0     0.0     1.0
ApplicantIncome    5849.0  4583.0  3000.0  2583.0  6000.0  5417.0  ...  3232.0  2900.0  4106.0  8072.0  7583.0  4583.0
CoapplicantIncome     0.0  1508.0     0.0  2358.0     0.0  4196.0  ...  1950.0     0.0     0.0   240.0     0.0     0.0
LoanAmount          128.0   128.0    66.0   120.0   141.0   267.0  ...   108.0    71.0    40.0   253.0   187.0   133.0
Loan_Amount_Term    360.0   360.0   360.0   360.0   360.0   360.0  ...   360.0   360.0   180.0   360.0   360.0   360.0
Credit_History        1.0     1.0     1.0     1.0     1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     0.0
Property_Area         2.0     0.0     2.0     2.0     2.0     2.0  ...     0.0     0.0     0.0     2.0     2.0     1.0

[11 rows x 614 columns]

In [8]:
df.shape

(614, 13)

- model_selection : data 쪼개기(8:2 / 7:3)
    - test_size : test 비중
    - X_train : 과정 / y_train : 정답
    - X_test : test / y_test : 정답

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train , y_test = train_test_split(X, y, test_size=0.2)

- 8 : 2 로 데이터 나눠지는 것을 볼 수 있음

In [17]:
X_train.shape, X_test.shape

((491, 11), (123, 11))

In [18]:
y_train.shape , y_test.shape

((491,), (123,))

- 알고리즘에 학습 시키기

### 모델 생성 및 학습
* 모델 생성 : 변수 = DecisionTreeClassifier()
* 학습 : 변수.fit(X_train, y_train)
    - 문제와 정답을 알고리즘에 학습
* 예측 : 변수.predict(X_test)
    - 확인용 문제를 predict에 넣으면 정답을 알려줌
- DecisionTreeClassifier : 분류 / DecisionTreeRegressor : 회귀

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [22]:
pred = dtc.predict(X_test)
pred

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int64)

- 예측 값과 정답 비교
    - accuracy_score : 정확도 나타냄

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test, pred)

0.7235772357723578

- 예측 값으로 정답 넣어주기

In [26]:
df_test = pd.read_csv("data/loan_test_cleaning.csv")
df_test.head().T

                        0       1       2       3       4
Loan_ID               0.0     1.0     2.0     3.0     4.0
Gender                1.0     1.0     1.0     1.0     1.0
Married               1.0     1.0     1.0     1.0     0.0
Dependents            0.0     1.0     2.0     2.0     0.0
Education             0.0     0.0     0.0     0.0     1.0
Self_Employed         0.0     0.0     0.0     0.0     0.0
ApplicantIncome    5720.0  3076.0  5000.0  2340.0  3276.0
CoapplicantIncome     0.0  1500.0  1800.0  2546.0     0.0
LoanAmount          110.0   126.0   208.0   100.0    78.0
Loan_Amount_Term    360.0   360.0   360.0   360.0   360.0
Credit_History        1.0     1.0     1.0     1.0     1.0
Property_Area         2.0     2.0     2.0     2.0     2.0

In [27]:
df_test.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [28]:
f = [ 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area' ]
X_test = df_test[ f ]
X_test

     Gender  Married  Dependents  Education  ...  LoanAmount  Loan_Amount_Term  Credit_History  Property_Area
0         1        1           0          0  ...       110.0             360.0             1.0              2
1         1        1           1          0  ...       126.0             360.0             1.0              2
2         1        1           2          0  ...       208.0             360.0             1.0              2
3         1        1           2          0  ...       100.0             360.0             1.0              2
4         1        0           0          1  ...        78.0             360.0             1.0              2
..      ...      ...         ...        ...  ...         ...               ...             ...            ...
362       1        1           3          1  ...       113.0             360.0             1.0              2
363       1        1           0          0  ...       115.0             360.0             1.0              2
364       1        0           0          0  ...       126.0             360.0             1.0              1
365       1        1           0          0  ...       158.0             360.0             1.0              0
366       1        0           0          0  ...        98.0             180.0             1.0              0

[367 rows x 11 columns]

- dtc 가 기존에 있던 데이터 학습함

In [29]:
pred = dtc.predict( X_test )
pred

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

- 위 나온 정답을 추가해줌

In [30]:
df_test['Loan_Status'] = pred
df_test.head().T

                        0       1       2       3       4
Loan_ID               0.0     1.0     2.0     3.0     4.0
Gender                1.0     1.0     1.0     1.0     1.0
Married               1.0     1.0     1.0     1.0     0.0
Dependents            0.0     1.0     2.0     2.0     0.0
Education             0.0     0.0     0.0     0.0     1.0
Self_Employed         0.0     0.0     0.0     0.0     0.0
ApplicantIncome    5720.0  3076.0  5000.0  2340.0  3276.0
CoapplicantIncome     0.0  1500.0  1800.0  2546.0     0.0
LoanAmount          110.0   126.0   208.0   100.0    78.0
Loan_Amount_Term    360.0   360.0   360.0   360.0   360.0
Credit_History        1.0     1.0     1.0     1.0     1.0
Property_Area         2.0     2.0     2.0     2.0     2.0
Loan_Status           1.0     1.0     1.0     1.0     1.0

In [32]:
df_test.loc[0]

Loan_ID                 0.0
Gender                  1.0
Married                 1.0
Dependents              0.0
Education               0.0
Self_Employed           0.0
ApplicantIncome      5720.0
CoapplicantIncome       0.0
LoanAmount            110.0
Loan_Amount_Term      360.0
Credit_History          1.0
Property_Area           2.0
Loan_Status             1.0
Name: 0, dtype: float64

In [43]:
user = [[1.0, 1.0, 0.0, 0.0, 0.0, 100000.0, 0.0, 110.0, 360.0, 1.0, 2.0]]

In [44]:
dtc.predict( user )[0]

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

1

In [45]:
if dtc.predict( user )[0] == 0 :
    print("아쉽지만 불가합니다")
else:
    print("대출이 가능합니다")

대출이 가능합니다

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(